"use client";

/**
 * Printable Report — on-screen preview of the deterministic export model.
 * Official PDF/XLSX/Markdown artifacts are generated by the server routes.
 *
 * All figures come from AuditReport (deterministic engine). Zero LLM output.
 *
 * TRANSLATION SCOPE: the report BODY — the markdown behind the "Copy Markdown"
 * button — arrives already written from the engine (build-report.ts), and so do
 * the finding titles, the trend insights and the assumption sources rendered
 * below. What is translated here is this component's own chrome: the export
 * buttons, the section headings, the KPI labels, the table headers, the Excel
 * sheet names and column headers, and the disclaimer.
 */

import { useState } from "react";
import { DownloadSimple, FileText, Table } from "@phosphor-icons/react";
import { AuditReport, formatUSD, isQuickWin } from "@/engine/types";
import {
  SavingsByCategoryChart,
  CostByServiceChart,
  MonthProjectionChart,
} from "./report-charts";
import { useLocale } from "@/i18n/locale-provider";
import { formatPlural } from "@/i18n/translate";
import { CONFIDENCE_LABELS_I18N } from "@/i18n/labels";
import { formatDate } from "@/i18n/formatters";
import { findingPresentation } from "@/i18n/engine-presentation";

interface PrintableReportProps {
  report: AuditReport;
  markdown: string;
  analysisId?: string;
  analysisToken?: string;
}

// ─── Component ────────────────────────────────────────────────────────────────

export function PrintableReport({ report, markdown, analysisId, analysisToken }: PrintableReportProps) {
  const { t, locale, dict } = useLocale();
  const quickWins = report.findings.filter(isQuickWin);
  const topActions = [...report.findings]
    .filter((f) => f.estimatedMonthlySavingsUSD > 0 || f.category === "ai-visibility")
    .sort((a, b) => b.priorityScore - a.priorityScore)
    .slice(0, 3);

  const [copied, setCopied] = useState(false);
  const [downloading, setDownloading] = useState<"pdf" | "xlsx" | null>(null);
  const [exportError, setExportError] = useState<string | null>(null);

  const exportUrl = (format: "pdf" | "xlsx" | "md") =>
    analysisId ? `/api/exports/${analysisId}/${format}?locale=${locale}` : null;
  const authHeaders: HeadersInit | undefined = analysisToken
    ? { "X-Nimbus-Analysis-Token": analysisToken }
    : undefined;

  const download = async (format: "pdf" | "xlsx") => {
    const url = exportUrl(format);
    if (!url || !analysisToken) return;
    setDownloading(format);
    setExportError(null);
    try {
      const response = await fetch(url, { cache: "no-store", headers: authHeaders });
      if (!response.ok) throw new Error(response.status === 410 ? "ANALYSIS_EXPIRED" : "EXPORT_FAILED");
      const blob = await response.blob();
      const href = URL.createObjectURL(blob);
      const anchor = document.createElement("a");
      anchor.href = href;
      anchor.download =
        response.headers.get("Content-Disposition")?.match(/filename="?([^"]+)"?/)?.[1] ??
        `nimbus-report.${format}`;
      anchor.click();
      URL.revokeObjectURL(href);
    } catch {
      setExportError(locale === "es" ? "No se pudo generar el archivo. Vuelve a intentarlo." : "The file could not be generated. Try again.");
    } finally {
      setDownloading(null);
    }
  };

  const handleCopy = async () => {
    const url = exportUrl("md");
    let content = markdown;
    if (url && analysisToken) {
      const response = await fetch(url, { cache: "no-store", headers: authHeaders });
      if (response.ok) content = await response.text();
    }
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <>
      {/* Action bar — hidden in print */}
      <div className="no-print flex flex-wrap gap-3 mb-6">
        <button
          onClick={() => download("pdf")}
          disabled={!analysisId || !analysisToken || downloading !== null}
          className="btn-primary disabled:opacity-50"
        >
          <DownloadSimple size={18} aria-hidden="true" />
          {downloading === "pdf" ? t("common.loading") : t("report.printable.downloadPdf")}
        </button>
        <button
          onClick={() => download("xlsx")}
          disabled={!analysisId || !analysisToken || downloading !== null}
          className="btn-secondary disabled:opacity-50"
        >
          <Table size={18} aria-hidden="true" />
          {downloading === "xlsx" ? t("common.loading") : t("report.printable.downloadExcel")}
        </button>
        <button
          onClick={handleCopy}
          className="btn-secondary"
        >
          <FileText size={18} aria-hidden="true" />
          {copied ? t("common.copied") : t("report.printable.copyMarkdown")}
        </button>
      </div>
      {exportError && <p role="alert" className="mb-4 rounded-[10px] bg-danger-soft p-3 text-sm text-danger">{exportError}</p>}

      {/* Printable report */}
      <div id="printable-report" className="printable-report text-ink space-y-6">

        {/* Header */}
        <section className="print-section card-premium p-7">
          <div className="flex flex-wrap items-start justify-between gap-4">
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand mb-2">{t("report.printable.eyebrow")}</p>
              <h1 className="text-2xl font-semibold text-ink tracking-tight">{t("report.printable.title")}</h1>
            </div>
            {report.isFocusSource && (
              <span className="text-xs font-medium text-brand bg-brand-soft px-2.5 py-1 rounded-full shrink-0">{t("report.printable.focusBadge")}</span>
            )}
          </div>
          <div className="flex flex-wrap gap-x-8 gap-y-1 mt-4 text-sm text-ink-muted">
            <span>{t("report.printable.generated", { date: formatDate(report.generatedAt, locale) })}</span>
            <span>{t("report.printable.period", { start: formatDate(report.periodStart, locale), end: formatDate(report.periodEnd, locale) })}</span>
            <span>{t("report.printable.providers", { list: report.providers.map((p) => p.toUpperCase()).join(", ") })}</span>
          </div>
        </section>

        {/* Key figures */}
        <section className="print-section">
          <h2 className="text-sm font-semibold uppercase tracking-widest text-ink-faint mb-3">{t("report.printable.keyFigures")}</h2>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <KpiCard
              label={t("report.printable.kpiCost")}
              value={formatUSD(report.totalCostUSD)}
              sub={t("common.perMonth")}
            />
            <KpiCard
              label={t("report.printable.kpiSavings")}
              value={`${formatUSD(report.totalSavingsRange.conservative)}–${formatUSD(report.totalSavingsRange.optimistic)}`}
              sub={t("common.perMonth")}
              highlight
            />
            <KpiCard
              label={t("report.printable.kpiPercentage")}
              value={`${report.savingsPercentage}%`}
              sub={formatPlural(dict.report.printable.kpiQuickWins, quickWins.length)}
            />
          </div>
        </section>

        {/* Top 3 actions */}
        {topActions.length > 0 && (
          <section className="print-section card-premium p-6">
            <h2 className="font-semibold text-ink mb-4">{locale === "es" ? "Tres acciones prioritarias" : "Three priority actions"}</h2>
            <ol className="divide-y divide-line">
              {topActions.map((f, i) => {
                const presentation = findingPresentation(f, locale);
                return (
                <li key={f.id} className="flex items-start gap-3 text-sm py-3 first:pt-0 last:pb-0">
                  <span className="num w-5 shrink-0 font-semibold text-ink-faint mt-0.5">{i + 1}.</span>
                  <div className="flex-1 min-w-0">
                    <div className="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-0.5">
                      <span className="font-medium text-ink">{presentation.title}</span>
                      {f.estimatedMonthlySavingsUSD > 0 && (
                        <span className="text-positive num font-semibold shrink-0">
                          {formatUSD(f.savingsRange.conservative)}–{formatUSD(f.savingsRange.optimistic)}
                          {locale === "es" ? "/mes" : "/mo"}
                        </span>
                      )}
                    </div>
                    <span className="text-ink-faint text-xs">
                      {locale === "es" ? `esfuerzo ${f.effort} · riesgo ${f.risk}` : `${f.effort} effort · ${f.risk} risk`}
                    </span>
                  </div>
                </li>
              )})}
            </ol>
          </section>
        )}

        {/* Charts */}
        <section className="print-section card-premium p-6 space-y-8">
          <h2 className="font-semibold text-ink">{locale === "es" ? "Visualización del análisis" : "Analysis visualization"}</h2>
          <SavingsByCategoryChart report={report} />
          <CostByServiceChart report={report} />
          <MonthProjectionChart report={report} />
        </section>

        {/* Findings table */}
        <section className="print-section card-premium p-6">
          <h2 className="font-semibold text-ink mb-4">{locale === "es" ? "Hallazgos priorizados" : "Prioritized findings"}</h2>
          <div className="overflow-x-auto -mx-6 px-6">
            <table className="w-full text-sm border-collapse min-w-[560px]">
              <thead>
                <tr className="border-b border-line text-left">
                  <th className="py-2 pr-3 font-semibold text-ink-faint w-6">#</th>
                  <th className="py-2 pr-3 font-semibold text-ink-faint">{locale === "es" ? "Hallazgo" : "Finding"}</th>
                  <th className="py-2 pr-3 font-semibold text-ink-faint w-28 text-right">{locale === "es" ? "Ahorro/mes" : "Saving/mo"}</th>
                  <th className="py-2 pr-3 font-semibold text-ink-faint w-20">{locale === "es" ? "Esfuerzo" : "Effort"}</th>
                  <th className="py-2 font-semibold text-ink-faint w-36">{locale === "es" ? "Confianza" : "Confidence"}</th>
                </tr>
              </thead>
              <tbody>
                {report.findings.map((f, i) => (
                  <tr key={f.id} className="border-b border-line last:border-0 print-row">
                    <td className="num py-2.5 pr-3 text-ink-faint">{i + 1}</td>
                    <td className="py-2.5 pr-3 text-ink">{findingPresentation(f, locale).title}</td>
                    <td className="num py-2.5 pr-3 text-right text-positive font-medium whitespace-nowrap">
                      {f.estimatedMonthlySavingsUSD > 0
                        ? `${formatUSD(f.savingsRange.conservative)}–${formatUSD(f.savingsRange.optimistic)}`
                        : "—"}
                    </td>
                    <td className="py-2.5 pr-3 text-ink-muted">{f.effort}</td>
                    <td className="py-2.5 text-ink-muted">{CONFIDENCE_LABELS_I18N[locale][f.confidence]}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        {/* Trends */}
        {report.trendInsights.length > 0 && (
          <section className="print-section card-premium p-6">
            <h2 className="font-semibold text-ink mb-4">{locale === "es" ? "Tendencias detectadas" : "Detected trends"}</h2>
            <ul className="divide-y divide-line">
              {report.trendInsights.map((ins) => (
                <li key={ins.id} className="text-sm print-row py-3 first:pt-0 last:pb-0">
                  <p className={`font-medium ${ins.severity === "warning" ? "text-caution" : "text-ink"}`}>
                    {locale === "es" ? ins.title : "Billing trend requiring attention"}
                  </p>
                  <p className="text-ink-muted mt-0.5">
                    {locale === "es"
                      ? ins.detail
                      : "Review the period evidence and compare it with the workload or business event that drove the change."}
                  </p>
                </li>
              ))}
            </ul>
          </section>
        )}

        {/* Disclaimer */}
        <section className="print-section border-t border-line pt-4">
          <p className="text-xs text-ink-faint leading-relaxed max-w-3xl">
            {locale === "es"
              ? "Recomendaciones informativas basadas en datos de facturación. Todas las cifras son calculadas por el motor de reglas determinístico; la IA no genera números. Valida cada acción en tu entorno antes de aplicarla. El ahorro se muestra como un rango conservador–optimista basado en variables ajustables."
              : "Informational recommendations based on billing data. Every figure is calculated by the deterministic rules engine; AI does not generate numbers. Validate every action in your environment before applying it. Savings are shown as a conservative–optimistic range based on adjustable variables."}
          </p>
        </section>
      </div>
    </>
  );
}

// ─── KPI Card ─────────────────────────────────────────────────────────────────

function KpiCard({ label, value, sub, highlight }: {
  label: string; value: string; sub?: string; highlight?: boolean;
}) {
  return (
    <div className={`rounded-xl border p-4 ${highlight ? "border-brand bg-brand-soft" : "border-line bg-surface"}`}>
      <p className="text-xs text-ink-muted mb-1">{label}</p>
      <p className={`num text-lg font-bold ${highlight ? "text-brand" : "text-ink"} leading-tight`}>{value}</p>
      {sub && <p className="text-xs text-ink-faint mt-0.5">{sub}</p>}
    </div>
  );
}

// useState must be imported at the top — imported at line 1.
