"use client";

/**
 * Report Charts — visual representations of AuditReport data.
 *
 * All data comes from the deterministic engine (AuditReport); nothing is
 * generated by the LLM. Uses Recharts with the existing design token palette.
 *
 * Ink-dominant identity: color is reserved for money signals, so savings bars
 * use `positive`, the cost trend line uses `brand` (near-black ink, not a
 * competing hue), and the multi-slice donut steps through muted ink before
 * repeating a semantic accent.
 *
 * Recharts takes colours as PROPS (`fill`, `stroke`, tick/tooltip styles), not
 * as Tailwind classes, so the token classes can't reach them. They are read at
 * runtime from the CSS custom properties on <html> and recomputed whenever the
 * theme flips — see `useChartPalette`.
 */

import { useEffect, useState } from "react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
  Legend,
  LineChart,
  Line,
  CartesianGrid,
  TooltipProps,
} from "recharts";
import { AuditReport, formatUSD } from "@/engine/types";
import { useTheme } from "@/theme/theme-provider";
import { useT } from "@/i18n/locale-provider";

// ─── Design-token colours, read at runtime ───────────────────────────────────

type ChartPalette = {
  ink: string;
  inkMuted: string;
  inkFaint: string;
  inkFaintSoft: string;
  surface: string;
  surface3: string;
  line: string;
  brand: string;
  brandStrong: string;
  brandInk: string;
  positive: string;
  caution: string;
  danger: string;
};

/**
 * The light palette, verbatim from `:root` in globals.css. Two jobs:
 *  1. first paint / SSR, before the effect has read the real custom properties;
 *  2. printing — the print stylesheet re-declares the tokens as light, but a
 *     colour already read into a prop can't follow a media query, so a dark-theme
 *     user printing the report would get pale emerald bars on white paper.
 *
 * THIS IS A COPY OF `:root` AND HAS TO FOLLOW IT. A token edited in globals.css
 * and not mirrored here shows up as a chart drawn in the old palette — silently,
 * because nothing links the two. `inkFaint`/`inkFaintSoft` (96 111 133) and
 * `danger` (206 32 32) carry the contrast fix from `:root`; here they are only
 * chart fills, which already cleared the minimum, so mirroring them is
 * consistency rather than a defect.
 */
const LIGHT_PALETTE: ChartPalette = {
  ink: "#1e293b",
  inkMuted: "#475569",
  inkFaint: "#606f85",
  inkFaintSoft: "rgb(96 111 133 / 0.6)",
  surface: "#ffffff",
  surface3: "#f1f5f9",
  line: "rgba(15, 23, 42, 0.08)",
  brand: "#1c1f2e",
  brandStrong: "#0f1220",
  brandInk: "#ffffff",
  positive: "#047857",
  caution: "#b45309",
  danger: "#ce2020",
};

/**
 * Tokens are stored as bare "R G B" triplets so Tailwind can apply opacity
 * modifiers; `--line` and friends are complete colours. Wrap the former, pass
 * the latter through untouched.
 */
function token(styles: CSSStyleDeclaration, name: string, fallback: string, alpha?: number): string {
  const raw = styles.getPropertyValue(name).trim();
  if (!raw) return fallback;
  if (raw.includes("(")) return raw; // already a complete colour (rgba(...))
  return alpha === undefined ? `rgb(${raw})` : `rgb(${raw} / ${alpha})`;
}

function useChartPalette(): ChartPalette {
  const { resolved } = useTheme();
  const [palette, setPalette] = useState<ChartPalette>(LIGHT_PALETTE);
  // Print forces the light palette: see LIGHT_PALETTE's note.
  const [printing, setPrinting] = useState(false);

  useEffect(() => {
    const styles = getComputedStyle(document.documentElement);
    setPalette({
      ink: token(styles, "--ink", LIGHT_PALETTE.ink),
      inkMuted: token(styles, "--ink-muted", LIGHT_PALETTE.inkMuted),
      inkFaint: token(styles, "--ink-faint", LIGHT_PALETTE.inkFaint),
      // No token for the donut's lightest neutral step (was a raw #94a3b8), so
      // it is derived from ink-faint instead of adding a token for one slice.
      inkFaintSoft: token(styles, "--ink-faint", LIGHT_PALETTE.inkFaintSoft, 0.6),
      surface: token(styles, "--surface", LIGHT_PALETTE.surface),
      surface3: token(styles, "--surface-3", LIGHT_PALETTE.surface3),
      line: token(styles, "--line", LIGHT_PALETTE.line),
      brand: token(styles, "--brand", LIGHT_PALETTE.brand),
      brandStrong: token(styles, "--brand-strong", LIGHT_PALETTE.brandStrong),
      brandInk: token(styles, "--brand-ink", LIGHT_PALETTE.brandInk),
      positive: token(styles, "--positive", LIGHT_PALETTE.positive),
      caution: token(styles, "--caution", LIGHT_PALETTE.caution),
      danger: token(styles, "--danger", LIGHT_PALETTE.danger),
    });
    // `resolved` is the dependency that matters: the custom properties change
    // when <html data-theme> does, and nothing else re-renders this hook.
  }, [resolved]);

  useEffect(() => {
    const before = () => setPrinting(true);
    const after = () => setPrinting(false);
    window.addEventListener("beforeprint", before);
    window.addEventListener("afterprint", after);
    return () => {
      window.removeEventListener("beforeprint", before);
      window.removeEventListener("afterprint", after);
    };
  }, []);

  return printing ? LIGHT_PALETTE : palette;
}

/** Donut slice ramp: brand ink → money signals, neutral steps in between. */
function slicePalette(p: ChartPalette): string[] {
  return [
    p.brand,
    p.positive,
    p.inkFaint,      // neutral step, not another loud hue
    p.caution,
    p.brandStrong,
    p.inkFaintSoft,
    p.danger,        // reserved for the last/overflow slice
  ];
}

// ─── Shared tooltip ───────────────────────────────────────────────────────────

function USDTooltip({ active, payload, label }: TooltipProps<number, string>) {
  const t = useT();
  if (!active || !payload?.length) return null;
  return (
    <div className="bg-surface rounded-lg ring-1 ring-line px-3 py-2 text-xs">
      {/* `label` is the axis value: a category or service name produced by the
          engine, so it is printed as it arrives. */}
      {label && <p className="font-semibold text-ink mb-1 max-w-[200px] whitespace-normal">{label}</p>}
      {payload.map((p, i) => (
        <p key={i} className="text-ink-muted">
          {p.name}: <span className="num font-medium text-ink">{formatUSD(Number(p.value))}{t("common.perMonth")}</span>
        </p>
      ))}
    </div>
  );
}

// ─── 1. Horizontal bar chart — savings by category ───────────────────────────

export function SavingsByCategoryChart({ report }: { report: AuditReport }) {
  const palette = useChartPalette();
  const t = useT();
  const data = report.summaryByCategory
    .filter((c) => c.totalSavingsUSD > 0)
    .sort((a, b) => b.totalSavingsUSD - a.totalSavingsUSD)
    // `c.label` is the engine's category label and is used as the Y-axis tick as
    // it comes; translating category names is the engine's phase, not this one.
    .map((c) => ({ name: c.label, ahorro: c.totalSavingsUSD }));

  if (data.length === 0) return null;

  return (
    <div className="print-chart">
      <h4 className="text-sm font-semibold text-ink mb-3">{t("report.charts.savingsByCategory")}</h4>
      <ResponsiveContainer width="100%" height={Math.max(160, data.length * 38)}>
        <BarChart
          data={data}
          layout="vertical"
          margin={{ top: 0, right: 16, left: 8, bottom: 0 }}
        >
          <XAxis
            type="number"
            tickFormatter={(v) => formatUSD(v)}
            tick={{ fontSize: 11, fill: palette.inkMuted }}
            axisLine={false}
            tickLine={false}
          />
          <YAxis
            type="category"
            dataKey="name"
            width={190}
            tick={{ fontSize: 11, fill: palette.inkMuted }}
            axisLine={false}
            tickLine={false}
          />
          <Tooltip content={<USDTooltip />} cursor={{ fill: palette.surface3 }} />
          {/* `dataKey` is the field name in `data` — an identifier. `name` is the
              series label the tooltip prints, so that one is translated. */}
          <Bar dataKey="ahorro" name={t("report.charts.savingsSeries")} radius={[0, 4, 4, 0]} fill={palette.positive} />
        </BarChart>
      </ResponsiveContainer>
    </div>
  );
}

// ─── 2. Donut chart — cost by service (top 6 + Otros) ───────────────────────

export function CostByServiceChart({ report }: { report: AuditReport }) {
  const palette = useChartPalette();
  const t = useT();
  const slices = slicePalette(palette);
  const services = report.summaryByService
    .filter((s) => s.totalCostUSD > 0)
    .sort((a, b) => b.totalCostUSD - a.totalCostUSD);

  if (services.length === 0) return null;

  const top6 = services.slice(0, 6);
  const others = services.slice(6);
  const othersTotal = others.reduce((s, x) => s + x.totalCostUSD, 0);

  const data = [
    // Slice names are cloud service names shortened for the legend — product
    // names, so they stay exactly as the billing file spells them.
    ...top6.map((s) => ({
      name: s.service.replace("Amazon ", "").replace("AWS ", "").replace("Microsoft.", ""),
      value: s.totalCostUSD,
    })),
    // The overflow slice is the one label this chart writes itself.
    ...(othersTotal > 0 ? [{ name: t("report.charts.otherServices"), value: othersTotal }] : []),
  ];

  const RADIAN = Math.PI / 180;
  const renderLabel = ({
    cx, cy, midAngle, innerRadius, outerRadius, percent,
  }: { cx: number; cy: number; midAngle: number; innerRadius: number; outerRadius: number; percent: number }) => {
    if (percent < 0.06) return null;
    const radius = innerRadius + (outerRadius - innerRadius) * 0.55;
    const x = cx + radius * Math.cos(-midAngle * RADIAN);
    const y = cy + radius * Math.sin(-midAngle * RADIAN);
    return (
      // `brand-ink` rather than a fixed white: every slice colour is dark in the
      // light theme and light in the dark one, which is exactly the inversion
      // brand-ink already encodes (white on light, near-black on dark).
      <text x={x} y={y} fill={palette.brandInk} textAnchor="middle" dominantBaseline="central" fontSize={10} fontWeight={600}>
        {(percent * 100).toFixed(0)}%
      </text>
    );
  };

  return (
    <div className="print-chart">
      <h4 className="text-sm font-semibold text-ink mb-3">{t("report.charts.costByService")}</h4>
      <ResponsiveContainer width="100%" height={260}>
        <PieChart>
          <Pie
            data={data}
            cx="50%"
            cy="45%"
            innerRadius={60}
            outerRadius={100}
            dataKey="value"
            labelLine={false}
            label={renderLabel as unknown as boolean}
          >
            {data.map((_, i) => (
              <Cell key={i} fill={slices[i % slices.length]} />
            ))}
          </Pie>
          <Tooltip
            formatter={(value: number) => [
              formatUSD(value) + t("common.perMonth"),
              t("report.charts.costSeries"),
            ]}
            // This one uses Recharts' default tooltip chrome (the bar/line charts
            // use <USDTooltip/>, which is Tailwind-classed), so background and ink
            // have to be handed over explicitly or it stays a white box in dark.
            contentStyle={{
              fontSize: 12,
              borderRadius: 8,
              border: `1px solid ${palette.line}`,
              backgroundColor: palette.surface,
              color: palette.ink,
            }}
            itemStyle={{ color: palette.ink }}
            labelStyle={{ color: palette.ink }}
          />
          <Legend
            formatter={(value) => <span style={{ fontSize: 11, color: palette.inkMuted }}>{value}</span>}
            iconType="circle"
            iconSize={8}
          />
        </PieChart>
      </ResponsiveContainer>
    </div>
  );
}

// ─── 3. Line chart — month-end projection ────────────────────────────────────

export function MonthProjectionChart({ report }: { report: AuditReport }) {
  const palette = useChartPalette();
  const t = useT();
  // Look for month-projection trend insight for annotation
  const projInsight = report.trendInsights.find((t) => t.type === "month-projection");

  // Build daily cost series from insight evidence, or skip if not enough data.
  // We use period avg + projection as a simple 2-point line.
  if (!projInsight) return null;

  // Parse values from evidence: "Promedio diario del periodo completo (N días): $X."
  // These two patterns match the ENGINE's own Spanish wording, so they are not
  // translated: they are a contract with build-report.ts, not text for a reader.
  // They will have to move in step with the engine when its output is localised.
  const avgMatch = projInsight.evidence.match(/Promedio diario últimos 7 días:.*?=\s*\$([\d,]+\.\d+)/);
  const wholeAvgMatch = projInsight.evidence.match(/Promedio diario del periodo completo.*?:\s*\$([\d,]+\.\d+)/);

  if (!avgMatch || !wholeAvgMatch) return null;

  const recentAvg = parseFloat(avgMatch[1].replace(/,/g, ""));
  const periodAvg = parseFloat(wholeAvgMatch[1].replace(/,/g, ""));

  // `semana` and `costo` are the data keys Recharts addresses; the values are the
  // three X-axis labels this chart writes itself, so those are translated.
  const data = [
    { semana: t("report.charts.periodAverage"), costo: Math.round(periodAvg * 100) / 100 },
    { semana: t("report.charts.last7DaysAverage"), costo: Math.round(recentAvg * 100) / 100 },
    { semana: t("report.charts.projection30Days"), costo: Math.round(recentAvg * 30 * 100) / 100 },
  ];

  return (
    <div className="print-chart">
      <h4 className="text-sm font-semibold text-ink mb-1">{t("report.charts.monthProjection")}</h4>
      {/* The insight headline is engine text. */}
      <p className="text-xs text-ink-muted mb-3">{projInsight.title}</p>
      <ResponsiveContainer width="100%" height={180}>
        <LineChart data={data} margin={{ top: 4, right: 16, left: 8, bottom: 0 }}>
          {/* surface-3, not `line`: its light value is literally the #f1f5f9 the
              grid used, and in dark it stays a faint step above the page. */}
          <CartesianGrid strokeDasharray="3 3" stroke={palette.surface3} />
          <XAxis dataKey="semana" tick={{ fontSize: 10, fill: palette.inkMuted }} axisLine={false} tickLine={false} />
          <YAxis
            tickFormatter={(v) => formatUSD(v)}
            tick={{ fontSize: 10, fill: palette.inkMuted }}
            axisLine={false}
            tickLine={false}
          />
          <Tooltip content={<USDTooltip />} />
          <Line
            type="monotone"
            dataKey="costo"
            name={t("report.charts.costSeries")}
            stroke={palette.brand}
            strokeWidth={2}
            dot={{ r: 4, fill: palette.brand }}
            activeDot={{ r: 6 }}
          />
        </LineChart>
      </ResponsiveContainer>
    </div>
  );
}
